owner: freispace
repo: uptime-status
user-agent: freispace

sites:
  - name: "Website"
    url: https://freispace.com/de/
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.svg
    
  - name: "Application"
    url: $STATUS_APP_URL_PWA
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "API"
    url: $STATUS_APP_URL_API
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/api.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "Database"
    url: $STATUS_APP_URL_DB
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/db.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "Cache"
    url: $STATUS_APP_URL_CACHE
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/cache.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "Storage"
    url: $STATUS_APP_URL_S3
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/storage.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "Realtime communication"
    url: $STATUS_APP_URL_SSE
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/sse.svg
    headers:
      - "Accept: application/json"
      - "$STATUS_APP_HEADER"
      
  - name: "E-mail service"
    url: $EMAIL_SERVICE_URL
    icon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/email.svg
    headers:
      - "Accept: application/json"
      - "api-key: $EMAIL_SERVICE_API_KEY"

status-website:
  cname: status.freispace.com
  logoUrl: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/freispace-logo.svg
  favicon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.png
  faviconSvg: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.svg
  name: "Service status"
  introTitle: "**freispace** service status"
  introMessage: 
  links:
    - rel: stylesheet
      href: https://cdn.statically.io/gh/freispace/uptime-status/master/assets/freispace.css
  metaTags:
    - name: "robots"
      content: "noindex,nofollow,noodp"
  robotsText: "User-agent: * \n Disallow: /"
  
i18n:
  footer: "[Privacy Policy](https://freispace.com/de/datenschutz/) | [Terms](https://freispace.com/de/agb/) | [Legal](https://freispace.com/de/impressum/) | [Contact](https://freispace.com/de/kontakt/)"
