# Change these first
owner: freispace # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Website
    url: https://freispace.com
  - name: App
    url: https://app.freispace.com

status-website:
  cname: status.freispace.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "freispace Status"
  introTitle: "freispace live service status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://freispace.com
