owner: freispace
repo: uptime-status
user-agent: freispace

sites:
  - name: "Website"
    url: https://freispace.com/de/
  - name: "Web app"
    url: https://app.freispace.com
  - name: "E-mail service"
    url: $EMAIL_SERVICE_URL
    headers:
      - "Accept: application/json"
      - "api-key: $EMAIL_SERVICE_API_KEY"

status-website:
  cname: status.freispace.com
  logoUrl: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.svg
  favicon: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.png
  faviconSvg: https://raw.githubusercontent.com/freispace/uptime-status/master/assets/favicon.svg
  name: "freispace Status"
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://freispace.com
  metaTags:
    - name: "robots"
      content: "noindex,nofollow,noodp"
  robotsText: "User-agent: * \n Disallow: /"
